vich_uploader:
    db_driver: orm

    mappings:
        articles_images:
            uri_prefix: /uploads/articles_images
            upload_destination: '%kernel.project_dir%/public/uploads/articles_images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
