language: php
php:
    - '7.2'
before_install:
    - if [ -d "./.idea" ]; then echo "Forbidden idea folder found ! Please, ignore them globaly..."; exit 2; fi
    - if [ -d "./.env.local" ]; then echo "Forbidden configuration file found !"; exit 2; fi
    - if [ -d "./vendor" ]; then echo "Forbidden external libs folder found !"; exit 2; fi
    - if [ -d ".DS_Store" ]; then echo "Forbidden MacOS boring file found ! Please, ignore them globaly..."; exit 2; fi
install:
    - composer install
before_script:
    - phpenv config-add travis.php.ini
script:
    - ./bin/phpcs
    - ./bin/phpstan analyse src --level max
notifications:
    email:
        - TRAINER@wildcodeschool.fr
        - STUDENT_MAIL
branches:
    only:
        - master
        - dev
